packages:
  - 'admin'
  - 'api/apps/api'
  - 'api/apps/migration'
  - 'api/libs/tools/misc'
  - 'api/libs/tools/models'
  - 'api/libs/ports/email'
  - 'api/libs/ports/currency-cloud'
  - 'api/libs/ports/ifx'
  - 'app'
  - 'site'
  - 'ui'
