# CI Template for GitLab CI/CD 01ss
variables:
  APP_NAME: 'forex-api' 
  NAMESPACE: 'forex'
  CD_REPO: 'cdaxfx/DevOps/argocd/forex/cdax-api'

include:
  - project: 'cdaxfx/DevOps/ci-templates/commons'
    ref: v1.0.1
    file:
      - '/forex-defs.yaml'
  # - project: 'cdaxfx/DevOps/ci-templates/deploy'
  #   ref: v1.0.0
  #   file:
  #     - '/sonar-scanner.yaml'

stages:
  - prepare
  - build

start:api:
  stage: prepare
  only:
    changes:
      - apps/api/**/*
      - apps/api/*
      - Dockerfile
    refs:
      - main
      - develop
      - staging
  variables:
    SVC_NAME: "api"
  trigger:
    include:
      - local: .gitlab-ci-monorepo.yml
    strategy: depend

start:password-rotate-job:
  stage: prepare
  only:
    changes:
      - apps/password-rotate-job/**/*
      - apps/password-rotate-job/*
      - Dockerfile
    refs:
      - main
      - develop
      - staging
  variables:
    SVC_NAME: "password-rotate-job"
  trigger:
    include:
      - local: .gitlab-ci-monorepo.yml
    strategy: depend
