apiVersion: apps/v1
kind: Deployment
metadata:
  name: forex-frontend-tmp
  namespace: forex-frontend-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forex-frontend-tmp
      owner: cdax
      project: forex
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: forex-frontend-tmp
        owner: cdax
        project: forex
    spec:
      containers:
        - image:
          imagePullPolicy: IfNotPresent
          name: forex-frontend-tmp
          resources:
            limits:
              cpu: 200m
              memory: 600Mi
            requests:
              cpu: 100m
              memory: 300Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: forex-frontend-tmp
    argocd.argoproj.io/instance: forex-frontend-tmp-stg
    owner: cdax
    project: forex
  name: forex-frontend-tmp
  namespace: forex-frontend-prod
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: forex-frontend-tmp
    owner: cdax
    project: forex
